# Generated by Django 4.1.7 on 2023-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, verbose_name='Phone model')),
                ('img', models.ImageField(upload_to='images', verbose_name='Phone image')),
                ('price', models.PositiveBigIntegerField(verbose_name='Phone price')),
            ],
        ),
    ]
