# Generated by Django 4.1.7 on 2023-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60, verbose_name='User name')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='User email')),
                ('user_phone', models.CharField(max_length=60, verbose_name='User phone')),
                ('user_reviw', models.TextField(verbose_name='USer review')),
            ],
        ),
    ]
